# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e705dc92ca18e26897b9ef8e817e3bc9a34a6d60c02d282278de180ddb9e11559fcda5776fbdd4a943884bc580f762f9b06437a0025147eb5271180f84e8211b

test:
  secret_key_base: de372dc9f50352d785d337244ced28ee35225be221288e2302e02938bc3cdfc31c59d3b8c38ea3dccc6cffd3849ff77d4ca8113d572a54eaa8d49758f1d59dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
